version: '3.9'
name: app-placeholder
services:
  backend:
    container_name: backend-container
    build: backend
    environment:
      - ADDR=${ADDR:-0.0.0.0}
      - PORT=${BE_PORT:-8080}
      - APP_URL=http://${ADDR}:${FE_PORT:-3000}
      - REQUESTMAX=${REQUESTMAX:-9999}
    ports:
      - ${BE_PORT:-8080}:${BE_PORT:-8080}
  frontend:
    container_name: frontend-container
    build: frontend
    environment:
      - ADDR=${ADDR:-0.0.0.0}
      - PORT=${FE_PORT:-3000}
      - API_URL=http://${ADDR}:${BE_PORT:-8080}
    ports:
      - ${FE_PORT:-3000}:${FE_PORT:-3000}
    depends_on:
      - backend
